// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shekru_Task.Models;

public partial class DesignationGrade
{
    public int Dgid { get; set; }

    public string Gradename { get; set; }

    public int? Designationref { get; set; }

    public bool? IsActive { get; set; }

    public virtual Designation DesignationrefNavigation { get; set; }

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();
}