// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shekru_Task.Models;

public partial class Designation
{
    public int Did { get; set; }

    public string Designationname { get; set; }

    public bool? IsActive { get; set; }
}