// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shekru_Task.Models;

public partial class Employee
{
    public int Id { get; set; }

    public string Firstname { get; set; }

    public string Lastname { get; set; }

    public string EmailAddress { get; set; }

    public int? Phonenumber { get; set; }

    public int? DesignationRef { get; set; }

    public int? Graderef { get; set; }
}